### ISSUE TITLE
A question and an idea

### ISSUE THREAD

**Issue by hineios** [gazugafan/laravel-temporal#1]
Great package!
I have been using it for my latest project and it simply does what is supposed to do!

I do have a question and an idea, however.
I'll start with the question as it is simpler: how well does this work with laravel's native soft deletes?
I see no reason for it to not work as both functionalities are just applying scopes to queries but just wanted to be sure.

The second part is more of an idea. And it might well be outside the desired functionality of this package, but...

I am currently using this for product version keeping. And started thinking, what if I want to schedule a campaign where all products have a 50% discount after 20-5-2018 and come back to normal after 30-5-2018?
I would be a great functionality to have, the ability to create versions in the future.
The first impact I see is the scope added to get the current version, it would have to work something similar to the get version at date.
I'd like to know your thoughts on this matter 😃

**Comment by gazugafan** [comment]
Thanks, glad you like it!

I THINK this should work fine with laravel's native soft deletes, but I haven't tried it, and I don't think I'd want to make it work if there was a problem. I feel like deleting a temporal record should just make it no longer exist in the present (set it's temporal_end to now). That effectively accomplishes the same thing, right? The "deleted" record no longer exists, but you can still get to it (using ```latestVersion()```) and restore the latest version if you need to (using ```restore()```). Give it a try, though! If it doesn't work like you expect, feel free to send me a pull request if you come up with a fix.

I like your future version scheduling idea, but yeah I think it's outside the scope of this for now. I worry it would complicate things too much. Like... what happens if you modify the present version when there's a future version? Does the modified present version overwrite the future version? Does it not, and then your changes are lost once the future version becomes active? Are you not allowed to modify the present version if there's a future version, so you have to delete the future version first? Maybe there's a simple way to handle it all, but thinking about it right now it seems like it would get really messy. The idea IS intriguing, though. I can see how it could simplify certain scenarios. Maybe I'll revisit it someday!

That's not to say you can't schedule things yourself. I'd separate your campaigns out into its own table with extra start/end date fields for when the campaign starts/ends. Put the price of the product in there, and then check to see which campaign is active. Maybe fallback to the product's default price if no campaign is active. Something like that!

**Comment by hineios** [comment]
It effectively accomplishes the same thing! So it's okay.
I'll tinker about with it and will give you a response back. Probably next week.

Yes, I hadn't considered all those scenarios to be honest 😄 
Those are all good question! If programming taught me something is that somewhere in the world somebody struggled with this. Maybe we can get some inspiration elsewhere.

And that's actually a great idea! I'll look into that option, thanks!

Either way, if you ever decide to do something like this, just give me a bump and I might be of some help.

**Comment by gazugafan** [comment]
I've had to deal with scheduling pretty extensively, but I never thought to do it using temporal models for some reason. I've always just thought of this more like version control... a way to keep a log of changes, and in specific cases to get things as they were at a certain date/time. I pair it with my ChangeLog library to keep a complete record of exactly who did what. So if suddenly we notice something is deleted or changed, we can see the full history of what happened and rollback if necessary. Without these things in place you're left wondering who did it, what went wrong, and the old versions are just gone so there's no way to retrieve the old data.

I think it almost makes more sense to have a separate scheduling library in addition to this... because you'd want to see who's scheduling things, right? Like... if if you schedule a campaign to start next week, and then suddenly you see the campaign is active today, you'd want to know who messed with your schedule and be able to rollback to how you had it. So many start/end dates, it's making my head hurt!

**Comment by hineios** [comment]
The version control and ability to see who did what is definitely a plus.
It does seem to be the best option to simply use some other mechanism to schedule promotions.

Thanks for all the advice!
